version: "3.9"

services:
  web:
    build: .
    command: python /bookstore-production-site-2/manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /bookstore-production-site-2
    working_dir: /bookstore-production-site-2
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
